FROM debian:bookworm
ENV ENV LOGLEVEL INFO
ENV VENV /venv
ENV PACKAGE pyff==2.1.4
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get -q update && apt-get -y upgrade && apt-get install -y locales python3 python3-venv python3-pip python3-setuptools git-core swig libyaml-dev libyaml-dev python3-dev build-essential libxml2-dev libxslt-dev libz-dev wget xmlstarlet
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN python3 -m venv ${VENV} && . ${VENV}/bin/activate && python3 -m pip install ${PACKAGE} && python3 -m pip install --upgrade pipdeptree pykcs11 && pipdeptree
ADD pyffd.sh /pyffd.sh
ADD mdx.fd /mdx.fd
ADD filter-idps.fd /filter-idps.fd
ADD filter-sps.fd /filter-sps.fd
RUN chmod a+x /pyffd.sh
ENTRYPOINT ["/pyffd.sh"]
