apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-volume
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
